### PR TITLE
Test for PR build

### PR DESCRIPTION
**Pull request by tgjonestx**
Test for PR build

### CODE REVIEW

**Comment by jplouis** [comment]
retest this

**Comment by skyrych** [comment]
Can one of the admins verify this patch?

**Comment by tgjonestx** [comment]
@skyrych - I am using this PR to test the Jenkins job http://test-jenkins.zenoss.eng:8080/job/Docker%20Images/job/centos-base-pull-request-develop/

**Comment by tgjonestx** [comment]
Retest this.

**Comment by tgjonestx** [comment]
add to whiltelist

**Comment by tgjonestx** [comment]
ok to test

**Pull request closed without merging**
